version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Woo
      - grep 'Woo' index.html
  post_build:
    commands:
      - echo Build completed on `date`