version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
    finally:
      - echo i am under final comment
  build:
    commands:
      - echo Build started on `date`
      - echo Woo
      - grep 'Woo' index.html
    finally:
      - echo i am under final comment
  post_build:
    commands:
      - echo Build completed on `date`
    finally:
      - echo i am under final comment final post build step
artifacts:
  files:
    - '**/*'